### ISSUE TITLE
I think solutions of Exercise 2.3.4 and 2.3.7 (c) are wrong

### ISSUE THREAD

**Issue by arduinocc04** [UlisseMini/understanding-analysis-solutions#2]
Your solutions have helped and will help me so much.  
But I think I found two errors in your solution.  
Could you check them?

Exercise 2.3.4  
`(a_n) -> 0` but your answer is when `a_n -> inf`  
Exercise 2.3.7 (c)  
if `b_n = 1/n`, `(b_n) -> 0` and `(1/b_n)` diverges.

**Comment by arduinocc04** [comment]
and I think we can't use order limit theorem in Exercise 2.3.3 because we don't know whether (y_n) converges.

**Comment by arduinocc04** [comment]
2.4.3 (a) too. I think roots of x^2 - x -2 = 0 are x = -1, x = 2

**Comment by arduinocc04** [comment]
2.4.5 (a) too. I think we can't show x_n - x_{n+1} >= 0 by showing (x_n - x_{n+1})^2 >= 0. Because (a-b)^2 = (b-a)^2.
I think we could prove it by using (x_n)^2 - (x_{n+1})^2 = (x_n + x_{n+1})(x_n - x_{n+1}) and x_n + x_{n+1} > 0.

**Comment by arduinocc04** [comment]
2.4.8 (a) too. your equation of `S_n` is start with `1`, but in problem, the sum start with `1/2`, so we should divide answer by 2.

**Comment by arduinocc04** [comment]
I think the solution of 2.5.2 (a) needs more explanation since there is no reason for every proper sequence to converges to same value.

**Comment by arduinocc04** [comment]
And I suggest to replace therefor with therefore

**Comment by UlisseMini** [comment]
Thanks for the comments! I'll review the stuff you've mentioned

**Comment by UlisseMini** [comment]
> Your solutions have helped and will help me so much. But I think I found two errors in your solution. Could you check them?
> 
> Exercise 2.3.4 `(a_n) -> 0` but your answer is when `a_n -> inf` Exercise 2.3.7 (c) if `b_n = 1/n`, `(b_n) -> 0` and `(1/b_n)` diverges.

[Fixed](https://github.com/UlisseMini/understanding-analysis-solutions/commit/a56982bc22d09571cb0ae076b81c2ecb39d162a3). I must have misread the question in a rush to solve it

**Comment by UlisseMini** [comment]
> and I think we can't use order limit theorem in Exercise 2.3.3 because we don't know whether (y_n) converges.

Good point, [Fixed](https://github.com/UlisseMini/understanding-analysis-solutions/commit/43ead37d107ad82a0772080700e50b03a5d20328)

**Comment by UlisseMini** [comment]
> 2.3.13 (c) too. I think `lim_{m -> inf} 1/min(m,n) = 1/n`

You're right, silly mistake on my part. I'll make it a todo for now till I get around to finding an example

**Comment by UlisseMini** [comment]
> 2.4.3 (a) too. I think roots of `x^2 - x -2 = 0` are `x = -1, x = 2`

Fixed

**Comment by arduinocc04** [comment]
Thanks!

**Comment by UlisseMini** [comment]
I've fixed everything you mentioned, Take a look to see if it's right. In 2.4.5 (a) I used a different approach, I don't see how your approach works, doesn't it assume what it's trying to prove in `(x_n)^2 - (x_{n+1})^2 > 0`? I could be misunderstanding

**Comment by UlisseMini** [comment]
Closing this because I think I've fixed everything, if you find more issues you can reopen or make a new issue. Thanks!
