### ISSUE TITLE
Exercise 3.3.6

### ISSUE THREAD

**Issue by eroicaleo** [UlisseMini/understanding-analysis-solutions#38]
Hi Ulisse,

I think this question asks 3 questions for each of (a), (b), (c).
E.g. for (a), the 3 statements are
(a.1) Every finite set has a maximum.
(a.2) Every compact set has a maximum.
(a.3) Every closed set has a maximum.

It seems you did not answer for the "finite" case.

Also for (b), the "sum" of two closed sets might not be closed. [Here](https://math.stackexchange.com/questions/124130/sum-of-two-closed-sets-in-mathbb-r-is-closed) is a counterexample.

**Comment by jesseli2002** [comment]
Thanks for catching that - addressed with PR #39.
