### ISSUE TITLE
Exercise 1.6.10c

### ISSUE THREAD

**Issue by sevenkyus** [UlisseMini/understanding-analysis-solutions#4]
Hi,

Thank you so much for the solutions! They have been really helpful as a reference. 

I just wanted to point out a possible error in the proof for Exercise 1.6.10 (c) - specifically, the step where any antichain of P(N) is expressed as the countable union of all A_L, where A_L is every subset of N in A with size L for some L in N. This only accounts for finite-sized elements of P(N), but not for infinite-sized elements of P(N) that can possibly be in A. One example would be the set of all even natural numbers, which doesn't belong in any A_L, but can exist as an element of an antichain.

**Comment by UlisseMini** [comment]
Good point! The proof is wrong, I'll fix this tomorrow if I have time (sorry for not responding earlier, I didn't get the notification for this issue)

**Comment by UlisseMini** [comment]
@jesseli2002 Fixed this, I guess if you procrastinate long enough on something open source someone else fixes it for you? :)
