### ISSUE TITLE
Excercise 1.3.4 b

### ISSUE THREAD

**Issue by tomvanlier** [UlisseMini/understanding-analysis-solutions#41]
In my opinion, the solution is wrong.
I think that : 

The formula in (a) does not  extend to the infinite case.

Take A_{n} = [n, n +1], then A_{n} is obviously nonempty and bounded above, but the infinite union becomes [0, + infty[ which is not bounded above .

**Comment by UlisseMini** [comment]
Good catch, weird; I seem to remember fixing this one
