### ISSUE TITLE
Exercise 2.2.3 (b)

### ISSUE THREAD

**Issue by OscarHesselberth** [UlisseMini/understanding-analysis-solutions#5]
The question is to disprove 'For all colleges in the United States, there exists a professor who gives every student
a grade of either A or B.' 

The answer that is given is 'Find a collage in the United States with a professor who has given a grade other then
an A or B.', but this does not seem correct to me, you would only check if there exists a professor that only not only grades A or B. But the statement would not be disproven if a college has a professor that only grades A or B, but also a professor which gives other grades. Wouldn't you need to find a college in the United States with no professors that only grade A or B.

**Comment by UlisseMini** [comment]
Thanks for the correction!
